name: Verify Jettons

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            jettons/*.yaml

      - name: Debug changed files
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Run verification
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          python scripts/verify_jetton.py ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Commit jettons.json
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          git config --global user.name "llraudseppll"
          git config --global user.email "llxll.stardust.llxll@gmail.com"
          git add jettons.json
          git commit -m "Update jettons.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
